### ISSUE TITLE
hello,about RealSense and distance

### ISSUE THREAD

**Issue by mk123qwe** [PINTO0309/MobileNet-SSDLite-RealSense-TF#1]
the number meters away  is the groundtruth and how to define it？
RealSense compute the number?
If I want to get the real position of the object，What do I need to do?
thanks！

**Comment by PINTO0309** [comment]
@mk123qwe

>RealSense compute the number?

Yes.
D435 measures the distance with infrared rays, so I think that it is ground truth.
It's measure the distance of the center coordinates of the detected object.
Because it is infrared, it can not measure normally if the surroundings are too bright.
Also, even if the distance is too close or too far it can not be measured normally.

**visualization_utils.py** 
```
meters = depth_frame.as_depth_frame().get_distance(int_xmin+int((int_xmax-int_xmin)/2), int_ymin+int((int_ymax-int_ymin)/2))
```
I think that you can understand by seeing the API specification, but there is no explanation.
http://intelrealsense.github.io/librealsense/doxygen/classrs2_1_1depth__frame.html#a5090d69d04ade6dd67175cae9b6bee9c

**Comment by mk123qwe** [comment]
Thank you again for your detailed answers.
I want to do a project on classification and pick up.
so I appreciate your research very much.
 I want to know the cost of hardware compare with TX2 .
The most important problem is that I need to reduces cost.

**Comment by PINTO0309** [comment]
@mk123qwe
I have no responsibility.
This is just an example.

Japanese yen.

RaspberryPi3 Model B:￥3,000
RealSense D435:￥28,000
HDMI Display 7inch:￥5,000

=============================
Total:￥36,000
+α　Operation cost

**Comment by mk123qwe** [comment]
test this:Tutorial to set up TensorFlow Object Detection API on the Raspberry Pi
https://github.com/PINTO0309/TensorFlow-Object-Detection-on-the-Raspberry-Pi

I ran the program successfully, showing the video, but I did not recognize the result and bbox.
and test simple code:
import tensorflow as tf
happy= tf.constant('Happy new year!')
sess = tf.Session()
sess.run(happy)

tensorflow works well

**Comment by PINTO0309** [comment]
Topics unrelated to this repository will be refused.
Please report the problem to the original fork repository.
